// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9vAczW5HWcQTNc0TUd7neLa-4bB_GS4g',
    appId: '1:81968705855:web:85620d07bb81fc6939a38a',
    messagingSenderId: '81968705855',
    projectId: 'bajfreight-system',
    authDomain: 'bajfreight-system.firebaseapp.com',
    storageBucket: 'bajfreight-system.firebasestorage.app',
    measurementId: 'G-30G4TX4ZQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAduDoBbwrQz9Fz1Y18n5cg11yvF9VcceQ',
    appId: '1:81968705855:android:2569bfa50f1ca4fd39a38a',
    messagingSenderId: '81968705855',
    projectId: 'bajfreight-system',
    storageBucket: 'bajfreight-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADG9VvV9JNenyRWXzvWey_ij-p7ESeJeM',
    appId: '1:81968705855:ios:a88ce2b897f6798c39a38a',
    messagingSenderId: '81968705855',
    projectId: 'bajfreight-system',
    storageBucket: 'bajfreight-system.firebasestorage.app',
    iosBundleId: 'com.example.ePod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADG9VvV9JNenyRWXzvWey_ij-p7ESeJeM',
    appId: '1:81968705855:ios:a88ce2b897f6798c39a38a',
    messagingSenderId: '81968705855',
    projectId: 'bajfreight-system',
    storageBucket: 'bajfreight-system.firebasestorage.app',
    iosBundleId: 'com.example.ePod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9vAczW5HWcQTNc0TUd7neLa-4bB_GS4g',
    appId: '1:81968705855:web:657eaeb19980ae7c39a38a',
    messagingSenderId: '81968705855',
    projectId: 'bajfreight-system',
    authDomain: 'bajfreight-system.firebaseapp.com',
    storageBucket: 'bajfreight-system.firebasestorage.app',
    measurementId: 'G-1KS93M0RBT',
  );

}