// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg_3Q3M6pJ7c_yC3DmxP_vT_25f18WAxo',
    appId: '1:100659409017:web:50f412df6d8e671d7ce4a8',
    messagingSenderId: '100659409017',
    projectId: 'baj-epod',
    authDomain: 'baj-epod.firebaseapp.com',
    storageBucket: 'baj-epod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUmMGwuGsQuG2R4dWTJddSekVP3c5iWU0',
    appId: '1:100659409017:android:92df72e0495cec917ce4a8',
    messagingSenderId: '100659409017',
    projectId: 'baj-epod',
    storageBucket: 'baj-epod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ77a8blG2JOXGadMp2_eFDsI15eEP2kQ',
    appId: '1:504831005939:ios:d67f823c4a1196493f5386',
    messagingSenderId: '504831005939',
    projectId: 'familyapp-8ec6f',
    storageBucket: 'familyapp-8ec6f.appspot.com',
    iosBundleId: 'com.example.ePod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ77a8blG2JOXGadMp2_eFDsI15eEP2kQ',
    appId: '1:504831005939:ios:d67f823c4a1196493f5386',
    messagingSenderId: '504831005939',
    projectId: 'familyapp-8ec6f',
    storageBucket: 'familyapp-8ec6f.appspot.com',
    iosBundleId: 'com.example.ePod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg_3Q3M6pJ7c_yC3DmxP_vT_25f18WAxo',
    appId: '1:100659409017:web:2415ff5ab73f6ab27ce4a8',
    messagingSenderId: '100659409017',
    projectId: 'baj-epod',
    authDomain: 'baj-epod.firebaseapp.com',
    storageBucket: 'baj-epod.firebasestorage.app',
  );

}